openapi: 3.0.0
info:
  title: API for mapped repair events platform (reparatur-initiativen.de)
  version: v1
servers:
  - url: https://www.reparatur-initiativen.de/api
    description: Production server
  - url: https://test.reparatur-initiativen.de/api
    description: Test server
paths:
  /v1/rest/workshops/city/{city}:
    get:
      tags:
      - "workshops"
      summary: "returns a list of workshops in a city"
      produces:
      - "application/json"
      parameters:
      - name: "city"
        in: "path"
        description: "city name (e.g. Berlin), case insensitve"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Workshop"
definitions:
  Workshop:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      city:
        type: "string"
      postalCode:
        type: "string"
      street:
        type: "string"
      street2:
        type: "string"
      landingPage:
        type: "string"
      logoUrl:
        type: "string"
      category:
        $ref: "#/definitions/Category"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      label:
        type: "string"
      iconUrl:
        type: "string"